// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "My.pb.h"
// @@protoc_insertion_point(imports)

@implementation MyRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MyRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Person ()
@property SInt32 age;
@property (strong) NSString* name;
@end

@implementation Person

- (BOOL) hasAge {
  return !!hasAge_;
}
- (void) setHasAge:(BOOL) _value_ {
  hasAge_ = !!_value_;
}
@synthesize age;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value_ {
  hasName_ = !!_value_;
}
@synthesize name;
- (instancetype) init {
  if ((self = [super init])) {
    self.age = 0;
    self.name = @"";
  }
  return self;
}
static Person* defaultPersonInstance = nil;
+ (void) initialize {
  if (self == [Person class]) {
    defaultPersonInstance = [[Person alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultPersonInstance;
}
- (instancetype) defaultInstance {
  return defaultPersonInstance;
}
- (BOOL) isInitialized {
  if (!self.hasAge) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAge) {
    [output writeInt32:1 value:self.age];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasAge) {
    size_ += computeInt32Size(1, self.age);
  }
  if (self.hasName) {
    size_ += computeStringSize(2, self.name);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Person*) parseFromData:(NSData*) data {
  return (Person*)[[[Person builder] mergeFromData:data] build];
}
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input {
  return (Person*)[[[Person builder] mergeFromInputStream:input] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersonBuilder*) builder {
  return [[PersonBuilder alloc] init];
}
+ (PersonBuilder*) builderWithPrototype:(Person*) prototype {
  return [[Person builder] mergeFrom:prototype];
}
- (PersonBuilder*) builder {
  return [Person builder];
}
- (PersonBuilder*) toBuilder {
  return [Person builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasAge) {
    [output appendFormat:@"%@%@: %@\n", indent, @"age", [NSNumber numberWithInteger:self.age]];
  }
  if (self.hasName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"name", self.name];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasAge) {
    [dictionary setObject: [NSNumber numberWithInteger:self.age] forKey: @"age"];
  }
  if (self.hasName) {
    [dictionary setObject: self.name forKey: @"name"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Person class]]) {
    return NO;
  }
  Person *otherMessage = other;
  return
      self.hasAge == otherMessage.hasAge &&
      (!self.hasAge || self.age == otherMessage.age) &&
      self.hasName == otherMessage.hasName &&
      (!self.hasName || [self.name isEqual:otherMessage.name]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasAge) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.age] hash];
  }
  if (self.hasName) {
    hashCode = hashCode * 31 + [self.name hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PersonBuilder()
@property (strong) Person* resultPerson;
@end

@implementation PersonBuilder
@synthesize resultPerson;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultPerson = [[Person alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultPerson;
}
- (PersonBuilder*) clear {
  self.resultPerson = [[Person alloc] init];
  return self;
}
- (PersonBuilder*) clone {
  return [Person builderWithPrototype:resultPerson];
}
- (Person*) defaultInstance {
  return [Person defaultInstance];
}
- (Person*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Person*) buildPartial {
  Person* returnMe = resultPerson;
  self.resultPerson = nil;
  return returnMe;
}
- (PersonBuilder*) mergeFrom:(Person*) other {
  if (other == [Person defaultInstance]) {
    return self;
  }
  if (other.hasAge) {
    [self setAge:other.age];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setAge:[input readInt32]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAge {
  return resultPerson.hasAge;
}
- (SInt32) age {
  return resultPerson.age;
}
- (PersonBuilder*) setAge:(SInt32) value {
  resultPerson.hasAge = YES;
  resultPerson.age = value;
  return self;
}
- (PersonBuilder*) clearAge {
  resultPerson.hasAge = NO;
  resultPerson.age = 0;
  return self;
}
- (BOOL) hasName {
  return resultPerson.hasName;
}
- (NSString*) name {
  return resultPerson.name;
}
- (PersonBuilder*) setName:(NSString*) value {
  resultPerson.hasName = YES;
  resultPerson.name = value;
  return self;
}
- (PersonBuilder*) clearName {
  resultPerson.hasName = NO;
  resultPerson.name = @"";
  return self;
}
@end

@interface Family ()
@property (strong) NSMutableArray<Person*> * personArray;
@end

@implementation Family

@synthesize personArray;
@dynamic person;
- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static Family* defaultFamilyInstance = nil;
+ (void) initialize {
  if (self == [Family class]) {
    defaultFamilyInstance = [[Family alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFamilyInstance;
}
- (instancetype) defaultInstance {
  return defaultFamilyInstance;
}
- (NSArray<Person*> *)person {
  return personArray;
}
- (Person*)personAtIndex:(NSUInteger)index {
  return [personArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  __block BOOL isInitperson = YES;
   [self.person enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    if (!element.isInitialized) {
      isInitperson = NO;
      *stop = YES;
    }
  }];
  if (!isInitperson) return isInitperson;
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:1 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(1, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Family*) parseFromData:(NSData*) data {
  return (Family*)[[[Family builder] mergeFromData:data] build];
}
+ (Family*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Family*)[[[Family builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Family*) parseFromInputStream:(NSInputStream*) input {
  return (Family*)[[[Family builder] mergeFromInputStream:input] build];
}
+ (Family*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Family*)[[[Family builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Family*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Family*)[[[Family builder] mergeFromCodedInputStream:input] build];
}
+ (Family*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Family*)[[[Family builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FamilyBuilder*) builder {
  return [[FamilyBuilder alloc] init];
}
+ (FamilyBuilder*) builderWithPrototype:(Family*) prototype {
  return [[Family builder] mergeFrom:prototype];
}
- (FamilyBuilder*) builder {
  return [Family builder];
}
- (FamilyBuilder*) toBuilder {
  return [Family builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"person"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  for (Person* element in self.personArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"person"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Family class]]) {
    return NO;
  }
  Family *otherMessage = other;
  return
      [self.personArray isEqualToArray:otherMessage.personArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.personArray enumerateObjectsUsingBlock:^(Person *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FamilyBuilder()
@property (strong) Family* resultFamily;
@end

@implementation FamilyBuilder
@synthesize resultFamily;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFamily = [[Family alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFamily;
}
- (FamilyBuilder*) clear {
  self.resultFamily = [[Family alloc] init];
  return self;
}
- (FamilyBuilder*) clone {
  return [Family builderWithPrototype:resultFamily];
}
- (Family*) defaultInstance {
  return [Family defaultInstance];
}
- (Family*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Family*) buildPartial {
  Family* returnMe = resultFamily;
  self.resultFamily = nil;
  return returnMe;
}
- (FamilyBuilder*) mergeFrom:(Family*) other {
  if (other == [Family defaultInstance]) {
    return self;
  }
  if (other.personArray.count > 0) {
    if (resultFamily.personArray == nil) {
      resultFamily.personArray = [[NSMutableArray alloc] initWithArray:other.personArray];
    } else {
      [resultFamily.personArray addObjectsFromArray:other.personArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FamilyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FamilyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PersonBuilder* subBuilder = [Person builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPerson:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray<Person*> *)person {
  return resultFamily.personArray;
}
- (Person*)personAtIndex:(NSUInteger)index {
  return [resultFamily personAtIndex:index];
}
- (FamilyBuilder *)addPerson:(Person*)value {
  if (resultFamily.personArray == nil) {
    resultFamily.personArray = [[NSMutableArray alloc]init];
  }
  [resultFamily.personArray addObject:value];
  return self;
}
- (FamilyBuilder *)setPersonArray:(NSArray<Person*> *)array {
  resultFamily.personArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FamilyBuilder *)clearPerson {
  resultFamily.personArray = nil;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
